version: '2'

services:

    abp_mvc:
        image: wenwengxk/abp-host:1.7
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
        ports:
            - "9903:80"
        volumes:
            - "./Mvc-Logs:/app/App_Data/Logs"